### ISSUE TITLE
Seems after updates ps scripts have a lot of issues

### ISSUE THREAD

**Issue by Lunnasi** [Microsoft/WingtipSaaS#53]
Hi! At this week after deploying template
1. catalog and template SQL server names were changed in portal: catalog-mt- && tenants1-mt-
2. at wtpConfig.psm1 file names not changed.
3. tenant DB in sharded pattern??? all default tenants at 1 DB in tenants-mt- server.
4. at provisioning script is errors with table definitions. 
5. Elastic Pool is not created automatically at deploying time.

**Comment by billgib** [comment]
Apologies, an incorrect ARM template was uploaded into the 'templates' storage container.  This has been rectified.  The template that you ran deployed a variation of the app that uses a multi-tenant database model rather than a database-per-tenant model, so doesn't deploy a pool by default.  That version will be made available in parallel to the database-per-tenant version in a separate GitHub repo.  Apologies for the confusion.
